### ISSUE TITLE
Vagrant-binding doesn't work with vagrant 1.2.7

### ISSUE THREAD

**Issue by kpelykh** [guigarage/vagrant-binding#2]
Would it be possible to synch vagrant-binding to work with the most recent version of vagrant? Simple update of gems breaks tests: 

testDummy(com.guigarage.vagrant.junit.RuleTest): org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `vms_ordered' for #Vagrant::Environment:0x7e32bcb6
  testFolderTemplates(com.guigarage.vagrant.configuration.VagrantFolderTemplateTest): (VagrantfileSyntaxError) There is a syntax error in the following Vagrantfile. The syntax error
  testFolderUriTemplates(com.guigarage.vagrant.configuration.VagrantFolderTemplateTest): (VagrantfileSyntaxError) There is a syntax error in the following Vagrantfile. The syntax error
  testWithoutFolderTemplates(com.guigarage.vagrant.configuration.VagrantFolderTemplateTest): (VagrantfileSyntaxError) There is a syntax error in the following Vagrantfile. The syntax error
